"""
LPFullRangeCurve2crv Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import LPFullRangeCurve2crvStrategy
except ImportError:
    from strategy import LPFullRangeCurve2crvStrategy

__all__ = [
    "LPFullRangeCurve2crvStrategy",
]
